# Generated by Django 3.0.2 on 2020-05-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_infectednode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infectednode',
            name='children',
        ),
        migrations.AddField(
            model_name='infectednode',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Source of this person's infection.", null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.InfectedNode'),
        ),
    ]
