# Generated by Django 3.0.2 on 2020-05-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_auto_20200504_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectednode',
            name='parent',
            field=models.ForeignKey(help_text="Source of this person's infection.", null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.InfectedNode'),
        ),
    ]
