# Generated by Django 3.0.2 on 2020-05-08 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0018_auto_20200504_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectednode',
            name='children',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=[], size=None),
        ),
    ]
