# Generated by Django 3.0.2 on 2020-05-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_auto_20200508_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infectednode',
            old_name='identifer',
            new_name='identifer',
        ),
    ]
