# Generated by Django 3.0.2 on 2020-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0023_auto_20200508_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infectednode',
            name='identifer',
        ),
        migrations.AddField(
            model_name='infectednode',
            name='identifier',
            field=models.CharField(default='', help_text='identifier of the person/virus in experiment.', max_length=10000),
            preserve_default=False,
        ),
    ]
