# Generated by Django 3.0.2 on 2020-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0024_auto_20200508_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='initial_infected',
            field=models.IntegerField(help_text='How many people in the population start out infected with the virus?'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='mortality_chance',
            field=models.FloatField(help_text='How likely is a patient infected with the virus likely to succumb?'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='reproductive_rate',
            field=models.FloatField(help_text='How effective is the virus at spreading between individuals?'),
        ),
    ]
